project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left: 
      - text: Hands-on Exercise
        menu:
          - text: Hands-on Exercise 1
            href: Hands-on_Ex/Hands-on_Ex1/Hands-on_Ex1.html

          - text: Hands-on Exercise 2
            href: Hands-on_Ex/Hands-on_Ex2/Hands-on_Ex2.html
            
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/Hands-on_Ex3/Hands-on_Ex3.html
            
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/Hands-on_Ex4/Hands-on_Ex4.html
            
          - text: Hands-on Exercise 5a
            href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5a.html
            
          - text: Hands-on Exercise 5b
            href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5b.html
            
          - text: Hands-on Exercise 5c
            href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5c.html
            
          - text: Hands-on Exercise 5d
            href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5d.html
            
          - text: Hands-on Exercise 5e
            href: Hands-on_Ex/Hands-on_Ex5/Hands-on_Ex5e.html            
                        
          - text: Hands-on Exercise 6
            href: Hands-on_Ex/Hands-on_Ex6/Hands-on_Ex6.html     
                        
          - text: Hands-on Exercise 7a
            href: Hands-on_Ex/Hands-on_Ex7/Hands-on_Ex7a.html 
            
          - text: Hands-on Exercise 7b
            href: Hands-on_Ex/Hands-on_Ex7/Hands-on_Ex7b.html 
            
          - text: Hands-on Exercise 7c
            href: Hands-on_Ex/Hands-on_Ex7/Hands-on_Ex7c.html 
            
          - text: Hands-on Exercise 8
            href: Hands-on_Ex/Hands-on_Ex8/Hands-on_Ex8.html      
            
          - text: Hands-on Exercise 9
            href: Hands-on_Ex/Hands-on_Ex9/Hands-on_Ex9.html     
                        
          - text: Hands-on Exercise 10
            href: Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html     
                        
      - text: In-class Exercise
        menu:
          - text: In-class Exercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Ex1.html

          - text: In-class Exercise 6
            href: In-class_Ex/In-class_Ex6/In-class_Ex6.html
            
          - text: In-class Exercise 7
            href: In-class_Ex/In-class_Ex7/In-class_Ex7.html            
            
      - text: Take-home Exercise
        menu:
          - text: Take-home Exercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Ex1.html

          - text: Take-home Exercise 2
            href: Take-home_Ex/Take-home_Ex2/Take-home_Ex2.html          
            
          - text: Take-home Exercise 3
            href: Take-home_Ex/Take-home_Ex3/Take-home_Ex3.html
            
          - text: Take-home Exercise 4
            href: Take-home_Ex/Take-home_Ex3/Take-home_Ex4.html            

    right:
      - href: index.qmd
        text: Home
    pinned: true
  back-to-top-navigation: true
  favicon: favicon.ico


format:
  html:
    theme: 
      - theme.scss
    css: styles.css
    toc: true
    toc-title: Contents
    toc-expand: true
    toc-depth: 5
    number-sections: true

    grid:
      margin-width: 400px
    

    
editor: visual

